data()
help(trees)
str(trees)
class(trees)
class(trees$Girth)
class(trees$Girthtrees$Heighttrees$Volume)
print(trees)
print(trees$Height)
min(trees$Girth)
min(trees$Height)
min(trees$Volume)
apply(trees,2,max)
apply(trees,1,max)
dim(trees)
ncol(trees)
nrow(trees)
names(trees)
summary(trees)
table(trees)
table(trees$Height)
range(trees$Height)

help(iris)
str(iris)
class(iris)
class(iris$Sepal.Length)
class(iris$Petal.Length)
print(iris)
print(iris$Species)
min(iris$Sepal.Length)
min(iris$Sepal.Width)
min(iris$Petal.Length)
min(iris$Petal.Width)
apply(iris,2,max)
apply(iris,1,max)
dim(iris)


data=read.csv(file = "//home//mca//Desktop//PA//sample.csv")
data
mean(data$Quantity)
mean(data$Price)
is.na(data)
mean(data$Price,na.rm = 'T')
